services:
  backend:
    restart: always
    ports:
      - "8000:8000"

  bot:
    restart: always

  frontend:
    build:
      target: dev
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/ 
            - dist/
            
        - action: rebuild
          path: ./frontend/package.json
          
        - action: rebuild
          path: ./frontend/package-lock.json