FROM alpine:latest

ARG PB_VERSION=0.29.3

RUN apk add --no-cache \
    unzip \
    ca-certificates

# download and unzip PocketBase
ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /pb/

COPY ./pb_migrations /pb/pb_migrations
COPY ./pb_hooks /pb/pb_hooks

RUN mkdir -p /pb/pb_public

EXPOSE 5432

# start PocketBase
CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:5432"]